//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System;

public class ChargerAI : MonoBehaviour {
	public Transform Enemy;
	public Player dude;
	private Vector2 enemyPosition;
	private double EnemyX, EnemyY, dudeX, dudeY;
	MoveController moveController;
	private Vector2 speed, distance;
	private Boolean agro;
	private Animator animator;
	private AttackController attackController;
	
	System.Random rnd;
	private double t, timer;
	
	public void start() {
		enemyPosition = Enemy.position;
		distance = new Vector2 (0, 0);
		speed = new Vector2 (0, 0);
		t = 10;
		timer = 5;
		agro = false;
		moveController = GetComponent<MoveController> ();
		rigidbody2D.mass = 5;
	}

	/* void OnCollisionEnter2D(Collision2D other) {
		Debug.Log ("enter");
		timer = 0;
		agro = true;
		speed = new Vector2(0,0);
		Double temp = 1;
		while (temp > 0) {
			temp -= Time.deltaTime;
		}
	}

	void OnCollisionExit2D(Collision2D other) {
		Debug.Log ("Exit");
				agro = false;
		}
	*/

	void Update() {
		rnd = new System.Random ();
		enemyPosition = Enemy.position;
		EnemyX = enemyPosition.x;
		EnemyY = enemyPosition.y;
		dudeX = dude.transform.position.x;
		dudeY = dude.transform.position.y;
		distance = new Vector2 ((float)(dudeX - EnemyX),(float)(dudeY - EnemyY));

		if (distance.magnitude < 3) {
			agro = true;
		}
		if (distance.magnitude > 3) {
			agro = false;
		}
		//playerPosition = dude.moveController.transform.position;

		//dude.OnCollisionStay2D
		if (agro) {
			speed = new Vector2(0,0);
			//dude.facing
			t = 50;
			while(t > 0) {
				t -= Time.deltaTime;
				speed = new Vector2(0,0);
			}
			double xdistance = EnemyX - dudeX;
			double ydistance = EnemyY - dudeY;
			speed = new Vector2(-3 * (float)(xdistance),-3 * (float)(ydistance));
			rigidbody2D.velocity = speed;
			timer = 25;
			while(timer > 0) {
				timer -= Time.deltaTime;

			}
			Debug.Log ("Stop the clock, the time is " + Time.deltaTime);
			Debug.Log ("Gotta go fast " + speed);
			speed = new Vector2 (0,0);
			//speed = new Vector2(0,0);
			//rigidbody2D.velocity = speed;
		}

		else {

			if (t <= 0.9) {
				if(rigidbody2D.velocity.magnitude != 0) {
					speed = new Vector2 (0, 0);
					t = 2;
					//rand 1.5-3?
				}
			else {
				//		if (playerPosition.magnitude - moveController.transform.position.magnitude > 10) {
				int rand = rnd.Next (1, 5);
				if (rand == 1) {
					speed = new Vector2 (2,0);
					t = 1;
				} else if (rand == 2) {
					speed = new Vector2 (-2,0);
					t=1;
				} else if (rand == 3) {
					speed = new Vector2 (0,2);
					t=1;
				} else {
					speed = new Vector2 (0,-2);
					t=1;
				}
				
				//Debug.Log (x.ToString ());
			}
		}
		
		else {
			t -= Time.deltaTime;
		}
			agro = false;
	rigidbody2D.velocity = speed;
	}
		//Debug.Log (speed);
		//this.transform.position = x;
	}
	
}

