//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;

namespace AssemblyCSharp

{
		public class Axe : MonoBehaviour
		{
		public AxeMan AxeDude;
		public Player player;
		private bool isAgro;
		private double DudeX, DudeY, idleX, idleY;
		private Vector2 idle;
		public double radius;
		private double speed, speedScale, angle;

				public void Start ()
				{
					angle = 0;
					speed = 2.5;
					speedScale = (0.1 * Math.PI) / speed;
				}

				public void Update() {
				if (AxeDude.currentHp () <= 0) {
				gameObject.SetActive (false);
				}
			//might be redundant to create vars then only use once, might change that
				DudeX = AxeDude.transform.position.x;
				DudeY = AxeDude.transform.position.y;
				idle = AxeDude.getIdle ();
				idleY = idle.y;
				idleX = idle.x;
				isAgro = AxeDude.getAgro ();

					
				if (isAgro) {

					angle += speedScale;
					double tempX = DudeX + Math.Sin (angle)*radius;
					double tempY = DudeY + Math.Cos (angle)*radius;
					float tempfX = (float)tempX;
					float tempfY = (float)tempY;
					transform.position = new Vector2(tempfX, tempfY);
					//transform.position.x = DudeX + Math.Sin (angle)*radius;
					//transform.position.y = DudeY + Math.Cos (angle)*radius;
				}
				else {
				angle = 0;
				float tempX = (float)idleX;
				float tempY = (float)idleY;
				transform.position = new Vector2(tempX, tempY);
				}
								
								
				}
		}
}

